let backup = [
    {
        email: "biotechsmile@gmail.com",
        password: "12321",
        clinic: {
            name: "Biotec Smile",
            address: "Abba Eban1",
            city: "Herzliya",
            country: "israel",
            postcode: "4672519",
            phone: "0508669692",
            email: "biotechsmile@gmail.com",
        },
        cases: [
            {
                patient_name: "Yaniv Avisal",
                caseid: "AF_P0001",
                status: "Pending",
                progress: "Planning",
                clinicid: 0,
                chat: "",
                doctor: "Gal Havkin",
                date: 1677638400000,
                patient_age: 50,
                patient_gender: "Male",
                teeths_color: "A2",
                note: "tooth 26, color A2, zirconia copy base+ porcelain ceramic feldsphatic. *take care about the distovestibular surface that is too straight and food gets in between the two teeth.",
                body_type: "case",
                type: "prosthesis",
            },
            {
                patient_name: "Stav Ring",
                caseid: "AF_P0002",
                status: "Pending",
                chat: "",
                progress: "Planning",
                clinicid: 0,
                doctor: "Gal Havkin",
                date: 1677446400000,
                patient_age: 35,
                patient_gender: "Female",
                teeths_color: "A1",
                note: "Prepare a rigid acrylic night splint with occlusal contacts in CR, Forward guidance in motion upper jaw",
                body_type: "case",
                type: "prosthesis",
            },
            {
                patient_name: "Salsat Ben Shmuel",
                caseid: "AF_P0007",
                status: "Pending",
                progress: "Manufacturing",
                clinicid: 0,
                chat: "",
                doctor: "Gal Havkin",
                date: 1676121600000,
                patient_age: 50,
                patient_gender: "Male",
                teeths_color: "A2",
                note: "tooth 16 color a2 zirconia copy+ porcelain ceramic feldspathic",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Ovadia Tubi",
                caseid: "AF_P0015",
                status: "Pending",
                progress: "Shipped",
                clinicid: 0,
                doctor: "Gal Havkin",
                date: 1674297600000,
                patient_age: 55,
                patient_gender: "Male",
                chat: "",
                teeths_color: "A1",
                note: "PMMA Tooths: 46-43 42-41 32-31 33-34 35-38 Color A1",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Nir Rokpler",
                caseid: "AF_P0014",
                status: "Pending",
                progress: "Shipped",
                doctor: "Gal Havkin",
                chat: "",
                date: 1674384000000,
                patient_age: 35,
                patient_gender: "Male",
                teeths_color: "A1",
                note: "Hello need to do mockup for crowns 17-27 and 37-47. i just need the mockup design, we will print it here. make for him a beautifull smile and morphology. also need to pick up a response a bit in the bite so he will see his tooths good.",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Mordehai Bereby",
                caseid: "AF_P0013",
                status: "Pending",
                chat: "",
                progress: "Shipped",
                doctor: "Gal Havkin",
                date: 1674384000000,
                patient_age: 47,
                patient_gender: "Male",
                teeths_color: "A1",
                note: "pfm crowns + porcelain ceramic feldsphatic tooths 15-25 (14,15,24,25 are pontics) tooths 46-46 (31,41,35,36) open embrasures in gingival like i told you that i want always. Color A1 thanks.",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Monica Raz",
                caseid: "AF_P0012",
                status: "Pending",
                progress: "Shipped",
                doctor: "Gal Havkin",
                date: 1674652800000,
                patient_age: 45,
                patient_gender: "Female",
                teeths_color: "A1",
                note: "pmma crowns Color A1, 15-14, 13-12, 22-23, 24-26",
                body_type: "case",
                chat: "",
                type: "prosthesis",
            },

            {
                patient_name: "Mona Abu Sahda",
                caseid: "AF_P0010",
                status: "Pending",
                progress: "Manufacturing",
                doctor: "Gal Havkin",
                date: 1675555200000,
                patient_age: 20,
                patient_gender: "Female",
                chat: "",
                teeths_color: "A1",
                note: "upper: 11-12, 13-15, 21-22, 23-25 lower: 41-43, 44-46, 31-33, 34-35 Color A1 open ambrasure on gingiva like i want always. porcelain ceramic",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Meytal Dagan",
                caseid: "AF_P0017",
                status: "Pending",
                progress: "Shipped",
                doctor: "Gal Havkin",
                date: 1673500800000,
                chat: "",
                patient_age: 35,
                patient_gender: "Female",
                teeths_color: "A2",
                note: "tooths 21-26 PMMA",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Mene",
                caseid: "AF_P0016",
                status: "Pending",
                progress: "Shipped",
                doctor: "Gal Havkin",
                chat: "",
                date: 1673500800000,
                patient_age: 60,
                patient_gender: "Male",
                teeths_color: "A3",
                note: "44-47 (45 is pontic) 34-37 (34 is pontic) PFM Crowns Open Ambrasure on cervically",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Ella Rubinov",
                caseid: "AF_P0005",
                status: "Pending",
                chat: "",
                progress: "Recieved",
                doctor: "Gal Havkin",
                date: 1676851200000,
                patient_age: 35,
                patient_gender: "Female",
                teeths_color: "A2",
                note: "tooth 34, color A2, zirconia base+ porcelain ceramic thanks",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Elinor Levy",
                caseid: "AF_P0004",
                status: "Pending",
                progress: "Planning",
                chat: "",
                doctor: "Gal Havkin",
                date: 1677024000000,
                patient_age: 35,
                patient_gender: "Female",
                teeths_color: "A2",
                note: "upper jaw: 13-23 (11 is pontic), 14-16, 24, 25-27 lower jaw: 43-33, 36-37, 46-47 color: A2 material: PMMA notes* - the scans arent perfect, maybe do an provisional eggshell instead, thanks open embrasures",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Eliezer Eli",
                caseid: "AF_P0009",
                status: "Pending",
                chat: "",
                progress: "Redesign",
                doctor: "Gal Havkin",
                date: 1675564800000,
                patient_age: 40,
                patient_gender: "Male",
                teeths_color: "A1",
                note: "hey, upper: 11-13, 14-15, 16-17, 21-23, 24-25, 26-27 lower: 41-43, 44-45, 46-47, 31-33, 34-35, 36-37 Color A1 open embrasure on gingiva like always. Zirconia with porcelain ceramic",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Dorit Lahmi",
                caseid: "AF_P0008",
                status: "Pending",
                progress: "Manufacturing",
                doctor: "Gal Havkin",
                date: 1675939200000,
                patient_age: 45,
                chat: "",
                patient_gender: "Female",
                teeths_color: "M2 - 3d master vita",
                note: "hey, need to do veeners porcelain ceramic for tooths: 12,13,14,22,23. we used - M2 - 3d master vita make it natural like her tooths, i sent you the photos of that case",
                teeths_translucency: "MT",

                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "David Avitan",
                caseid: "AF_P0006",
                status: "Pending",
                progress: "Recieved",
                chat: "",
                doctor: "Gal Havkin",
                date: 1676659200000,
                patient_age: 50,
                patient_gender: "Male",
                teeths_color: "D2",
                note: "hey, need to do tooth 46, color: D2-D3 (D2.5), zirconia base with porcelain ceramic. need to do good morphology.",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Dana Levy",
                caseid: "AF_P0003",
                status: "Pending",
                progress: "Planning",
                doctor: "Gal Havkin",
                date: 1677100800000,
                patient_age: 30,
                patient_gender: "Female",
                chat: "",
                teeths_color: "M1.5",
                note: "upper: 13-16 (15 is pontic) lower: 45-47 (46 is pontic) M1.5 - 3d master vita bleaching tooth shade key Material: Zirconia copy + porcelain ceramic feldsphatic building open embrasures",
                body_type: "case",
                type: "prosthesis",
            },

            {
                patient_name: "Dana Gvora",
                caseid: "AF_P0011",
                status: "Pending",
                progress: "Manufacturing",
                chat: "",
                doctor: "Gal Havkin",
                date: 1674374400000,
                patient_age: 40,
                patient_gender: "Female",
                teeths_color: "A1",
                note: "Upper 15-27 12-23 extraction Lower: 33-43 Eggshell 42-32 extraction A1",
                body_type: "case",
                type: "prosthesis",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0009",
                patient_name: "Adaya Zaguri",
                date: 1677446400000,
                patient_age: 33,
                patient_gender: "Female",
                note: "",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0010",
                chat: "",
                patient_name: "Ariel Klintseky",
                date: 1674979200000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to straight tooths, fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0011",
                chat: "",
                patient_name: "Avi Vaknin",
                date: 1674105600000,
                patient_age: 43,
                patient_gender: "Male",
                note: "hey, need to straight tooths,fix contacts and fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0012",
                patient_name: "Bar Ovadya",
                chat: "",
                date: 1674979200000,
                patient_age: 33,
                patient_gender: "Female",
                note: "need to straight tooths, fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0013",
                patient_name: "Binyamin Protski",
                date: 1674374400000,
                chat: "",
                patient_age: 24,
                patient_gender: "Male",
                note: "hey, this patient did in china, he still have more 9 aligners for lower jaw, he finished in upper jaw but as you see the results isnt good, so need to make treatment to straight only upper jaw. thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0014",
                patient_name: "Dafna Kalzen",
                date: 1675555200000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bite",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0015",
                patient_name: "Daniel Roach",
                date: 1673664000000,
                patient_age: 33,
                chat: "",
                patient_gender: "Female",
                note: "hey, need to straight tooths,fix contacts,bite. also save place for implant thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                chat: "",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0016",
                patient_name: "Dave Oknin",
                date: 1673664000000,
                patient_age: 26,
                patient_gender: "Male",
                note: "hey, need to do 2 options: option 1: only straight tooths option 2: straight tooths, fix contacts, fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0017",
                patient_name: "Eli Levy",
                chat: "",
                date: 1674374400000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to straight tooths, fix contacts, fix bite, save place for lower implant thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0018",
                patient_name: "Eliav Giladi",
                date: 1675862400000,
                chat: "",
                patient_age: 25,
                patient_gender: "Male",
                note: "very hard patient, need to do 2 options: option 1 - straight tooths only option 2 - fix class 3 with minicrews,elastics,straight tooths,fix bite and contacts",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0019",
                patient_name: "Eliezer Brazon",
                chat: "",
                date: 1675555200000,
                patient_age: 33,
                patient_gender: "Male",
                note: "need to straight tooths, fix contacts and bite",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0020",
                patient_name: "Elinor Eilat",
                date: 1677820800000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bites, (fix class 3 and open bite)",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0021",
                patient_name: "Elinor Zoukevski",
                date: 1677446400000,
                patient_age: 38,
                patient_gender: "Female",
                note: "hey, need to do 2 options: option 1: straight teeths on upper jaw only option 2: straight teeths on both jaws + save place for implant tooth 46, means to straight and move a bite tooth number 47 option 3: full treatment, straight tooths,fix bite and contacts, save place for implant tooth 46, means to straight and move a bite tooth number 47",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0022",
                patient_name: "Eman Mousri",
                date: 1677024000000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, her main problem is that tooth 22 is outside and lower jaw is not straight option 1: straight tooths only option 2: straight tooths,fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0023",
                patient_name: "Eyline Fittusi",
                chat: "",
                date: 1674374400000,
                patient_age: 28,
                patient_gender: "Female",
                note: "hey, need to straight tooths,fix contacts and bite. she did in china aligners but the results arent good. thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0024",
                patient_name: "Israel Sabag",
                date: 1673750400000,
                chat: "",
                patient_age: 35,
                patient_gender: "Male",
                note: "hello, he started with china as past, he have more 6 aligners in lower and he finished the aligners in upper, he was hard case. as you see he have a gap in 11-21, he want to close the gap, so need to add ipr and close the gap, i think its more 2-3 aligners thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0025",
                chat: "",
                patient_name: "Itam Haj",
                date: 1674489600000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to straight tooths, fix contacts and bite. thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0026",
                patient_name: "Itay Rubin",
                date: 1674979200000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to do 2 options: option 1: straight tooths only option 2: straing tooths,fix contacts,bite, fix crossbite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0027",
                chat: "",
                patient_name: "Korin Haviv",
                date: 1677024000000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need 2 options: option 1 - upper jaw only, straight tooths option 2- upper and lower, fix contacts,straight tooths,fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0028",
                patient_name: "Lian Harush",
                chat: "",
                date: 1675555200000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to fix open bite,straight tooths, fix contacts thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0029",
                patient_name: "Lily Diamant",
                date: 1673500800000,
                patient_age: 43,
                patient_gender: "Female",
                note: "need to straight tooths,fix contacts and fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0030",
                patient_name: "Limor Kabir",
                date: 1676102400000,
                chat: "",
                patient_age: 37,
                patient_gender: "Female",
                note: "hey, you did for her aligners but as you see the results arent like the treatment. please do new simulation and than create the aligners. straight tooths,fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0031",
                patient_name: "Lior Mesilati",
                date: 1676659200000,
                patient_age: 33,
                chat: "",
                patient_gender: "Female",
                note: "hey, need to do straight tooths,fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0032",
                patient_name: "Lital Barhanim",
                chat: "",
                date: 1674192000000,
                patient_age: 43,
                patient_gender: "Female",
                note: "hey, need to straight tooths and fix bite and contacts (fix openbite) - i belive its gonna be around to 3-4 months? she gonna do an implant after the treatment in lower jaw just to note thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0033",
                patient_name: "Malca Gardiani",
                date: 1673500800000,
                patient_age: 43,
                patient_gender: "Female",
                note: "need to straight tooths,fix contacts and fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0034",
                patient_name: "Maor Rivgen",
                date: 1676659200000,
                patient_age: 25,
                chat: "",
                patient_gender: "Male",
                note: "hey, need to straight tooths,fix contacts and bite he did in china and he finished, but we need to make it better thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0035",
                patient_name: "Miryam Binyamin",
                chat: "",
                date: 1677638400000,
                patient_age: 28,
                patient_gender: "Female",
                note: "hey, she finished her aligners and she need additional aligners. as you see that some minor fixes, need only to straight a bit the tooths, maximum i belive 2-4 aligners thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0036",
                patient_name: "Morin Ofir",
                date: 1675555200000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bite, close gaps",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0037",
                chat: "",
                patient_name: "Niv Ifat",
                date: 1674297600000,
                patient_age: 33,
                patient_gender: "Female",
                note: "need to straight, fix contacts, fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                chat: "",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0038",
                patient_name: "Noy Cohen",
                date: 1677734400000,
                patient_age: 28,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0039",
                patient_name: "Ofek David",
                date: 1677916800000,
                patient_age: 16,
                patient_gender: "Male",
                note: "hey, need to straight tooths, close gaps, fix bite and contacts (looks easy case only some months) thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0040",
                patient_name: "Ortal Jeane",
                date: 1673664000000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to do 2 options: option 1: only straight tooths, save place for implant if possible option 2: straight tooths, fix contacts,bite, save place for implant thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0041",
                patient_name: "Rachel Eindenzon",
                chat: "",
                date: 1675555200000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, close gaps, fix contacts and bite, and save place for implant in lower jaw for tooth 46",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0042",
                chat: "",
                patient_name: "Reut Ben Hamo",
                date: 1675641600000,
                patient_age: 38,
                patient_gender: "Female",
                note: "hello, need to straight tooths,fix contacts and bite. looks like need to expand upper arch about lower jaw try to do ipr for space thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0043",
                patient_name: "Rita Moshayev",
                date: 1673750400000,
                chat: "",
                patient_age: 38,
                patient_gender: "Female",
                note: "hey, she want only lower jaw to straight the tooths, make without extraction,maximum add more ipr also make more option of both jaws upper and lower, so il give her more option thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0044",
                patient_name: "Ronza Konpti",
                date: 1674374400000,
                patient_age: 38,
                chat: "",
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bite, save place for lower implant thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0045",
                patient_name: "Roy Bar",
                chat: "",
                date: 1674297600000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey did in china before, need to straight tooths,fix contacts and bite (its gonna be shorter) thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0046",
                patient_name: "Roy Siso",
                date: 1674384000000,
                chat: "",
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to straight tooths, close gaps, fix contacts and bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0047",
                patient_name: "Sapir Lavi",
                date: 1677024000000,
                patient_age: 33,
                chat: "",
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts and bite, close gaps thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0048",
                patient_name: "Sasha Ben Moyal",
                date: 1675555200000,
                patient_age: 33,
                patient_gender: "Male",
                chat: "",
                note: "hey, need to straight tooths,close gaps, fix contacts and fix bite",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0049",
                patient_name: "Shaked Levy",
                date: 1674105600000,
                patient_age: 33,
                chat: "",
                patient_gender: "Male",
                note: "hey, need to do 2 options: option 1: only straight tooths option 2: straight tooths, fix contacts, fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0050",
                patient_name: "Sharona Somchi",
                chat: "",
                date: 1676745600000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to do 3 options: option 1: straight tooths lower jaw only optition 2: straight tooths on boths arches option 3: straight tooths+fix contacts and bite maximum as possible thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                chat: "",
                caseid: "AF_CA0051",
                patient_name: "Shimrit Eliyahu",
                date: 1674979200000,
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix bite,contacts thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0052",
                patient_name: "Shira Kilzy",
                date: 1675862400000,
                patient_age: 33,
                patient_gender: "Female",
                chat: "",
                note: "hey, need to straight tooths, fix contacts and bite",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0053",
                patient_name: "Shoval Garame",
                date: 1673500800000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "need to straight tooths,fix contacts and fix bite thanks",
            },
            {
                type: "clearaligners",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Gal Havkin",
                caseid: "AF_CA0054",
                chat: "",
                patient_name: "Tamir Garame",
                date: 1673500800000,
                patient_age: 33,
                patient_gender: "Male",
                note: "hey, need to straight tooths he did in china and he finished, now he need more i think around to 1-3 upper and 3-5 lower thanks",
            },
        ],
    },
    {
        email: "mikifuchs@gmail.com",
        password: "12321",
        clinic: {
            name: "Dr.Miki Fuchs",
            address: "ARIE BROWN 10",
            city: "Petach Tikva",
            country: "israel",
            postcode: "4906329",
            phone: "+972512932514",
            email: "mikifuchs@gmail.com",
        },
        cases: [
            {
                patient_name: "Yeonathan Erlich",
                caseid: "AF_CA0004",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Miki Fuchs",
                date: 1676745600000,
                chat: "",
                patient_age: 20,
                patient_gender: "Male",
                note: "Hi, another case of first priority alignment Upper arch alignment Second priority is reducing overbite Finally midline correction Thanks Mickey",
                type: "clearaligners",
            },
            {
                patient_name: "Tamir Levy",
                caseid: "AF_CA0005",
                status: "Pending",
                progress: "Pending",
                chat: "",
                doctor: "Dr. Miki Fuchs",
                date: 1677369600000,
                patient_age: 43,
                patient_gender: "Male",
                note: "hello, need to close gaps, straight teeth both jaws *just to note there is some distortion in teeth 43 and 44, so please try to fix it and adjust the bite thanks",
                type: "clearaligners",
            },
            {
                patient_name: "Shay Halperan",
                caseid: "AF_CA0006",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Miki Fuchs",
                date: 1677369600000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to close the diastema (gaps) in upper jaw *take in considiration exctraction one of the 42-32",
                type: "clearaligners",
            },
            {
                patient_name: "Moran Groner",
                caseid: "AF_CA0007",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Miki Fuchs",
                date: 1673500800000,
                chat: "",
                patient_age: 33,
                patient_gender: "Female",
                note: "hey, need to straight tooths, fix contacts,bite, midline thanks",
                type: "clearaligners",
            },
            {
                patient_name: "Marina Roza",
                caseid: "AF_CA0008",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. Miki Fuchs",
                date: 1677369600000,
                chat: "",
                patient_age: 43,
                patient_gender: "Female",
                note: "hey, i want 2 options: 1. only straightening upper jaw 2. straightening 2 jaws and fix the bite and contacts thanks",
                type: "clearaligners",
            },
        ],
    },
    {
        email: "ephraimdr@gmail.com",
        password: "12321",
        clinic: {
            name: "Dr.Tzur",
            address: "Hzomet 8",
            city: "Kfar Saba",
            country: "israel",
            postcode: "4426708",
            phone: "09-7456666",
            email: "ephraimdr@gmail.com",
        },
        cases: [
            {
                patient_name: "kobi rozen",
                caseid: "AF_CA0001",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. drtzur",
                date: 1676486400000,
                patient_age: 0,
                chat: "",
                patient_gender: "Male",
                note: "שלום נשמח להצעה לגבי יישור שיניים בלסת תחתונה בלבד דחוף תודה רבה",
                type: "clearaligners",
            },
            {
                caseid: "AF_CA0002",
                patient_name: "idan avrahami",
                status: "Pending",
                progress: "Pending",
                doctor: "Dr. drtzur",
                chat: "",
                date: 1675939200000,
                patient_age: 28,
                patient_gender: "Male",
                note: "מטופל עם תלונה אסתטית לגבי הרווחים. מעוניין לסגור אותם שיניים קטנות יחסית טס בספטמבר ללמוד בחול האם אפשרי יישור שיניים עי קשתיות שקופות והאם מצריך הרבה ביקורות והשחזות סלקטיביות? תודה דר רון",
            },
            {
                patient_name: "Dana Ohayon",
                caseid: "AF_CA0003",
                status: "Pending",
                progress: "Pending",
                patient_age: 31,
                patient_gender: "Female",
                date: 1675862400000,
                doctor: "Dr. drtzur",
                note: "אשמח לדעת אם המקרה מתאים ליישור לסת עליונה בלבד. אם לא ויש פגיעה בסגר נעשה 2 לסתות אשמח לעדכון במספר הפלטות",
                chat: "",
            },
        ],
    },
];

module.exports = { backup };

// let { backup } = require("./setup");
// (async () => {
//     for (let u of backup) {
//         let salt = bcrypt.genSaltSync(10);
//         let user = await User.create({ email: u.email, fullname: "", password: hashPassword(u.password, salt), salt: salt });
//         console.log(`User #${u.email} created`);
//         let clinic = await Clinic.create({ userid: user._id, name: u.clinic.name, address: u.clinic.address, city: u.clinic.city, country: u.clinic.country, postcode: u.clinic.postcode, phone: u.clinic.phone, email: u.clinic.email });
//         console.log(`Clinic #${u.clinic.name} created`);

//         for (let c of u.cases) {
//             await Case.create({
//                 ...c,
//                 userid: user._id,
//                 clinicid: clinic._id,
//                 chat: undefined,
//             });
//             console.log(`Case #${c.caseid} created`);
//         }
//     }
// })();
